# Docs: https://sw.kovidgoyal.net/kitty/overview
shell /usr/bin/fish

# BEGIN_KITTY_THEME
# Matugen
include current-theme.conf
include themes/matugen.conf
# END_KITTY_THEME

window_padding_width 5
hide_window_decorations yes
background_opacity 0.8
remember_window_size no
confirm_os_window_close 0

font_family JetBrains Maple Mono
font_size 15

cursor_trail 1
cursor_shape block
shell_integration no-cursor
